# Generated by Django 4.0.5 on 2022-07-01 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileBuilding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='users/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('course_name', models.TextField(blank=True, max_length=500)),
                ('course_duration', models.IntegerField()),
                ('course_passoutyear', models.CharField(max_length=4, null=True)),
                ('course_percentage', models.FloatField()),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('duration', models.IntegerField()),
                ('job_description', models.TextField(blank=True, max_length=500)),
                ('salary', models.IntegerField()),
                ('project_name', models.CharField(blank=True, max_length=100)),
                ('duration_project', models.IntegerField()),
                ('project_description', models.TextField(blank=True, max_length=500)),
                ('role', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
