# Generated by Django 4.0.5 on 2022-07-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileBuilding', '0005_alter_profile_course_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='download.png', null=True, upload_to='users/'),
        ),
    ]
